{application, oserl,
    [{description, "Open SMPP Erlang Library"},
     {vsn, "1.3"},
     {id, "oserl"},
     {modules, [base_syntax, 
                gen_esme, 
                gen_esme_session, 
                gen_smsc, 
                gen_smsc_session,
                operation,
                param_syntax,
                pdu_syntax,
                sm,
                smpp_error,
                smpp_log]},
     {registered, []},
     {applications, [kernel, stdlib, common_lib]}]}.